# start container: docker compose up -d --build
# stop container: docker compose down
version: "3.9"

services:

  nginx:
    image: nginx:latest
    restart: always
    container_name: client-loadbalancer
    ports:
      - 8080:8080
    depends_on:
      - client
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - loadbalancer-network

  client:
    build: ./src/calendar-client
    restart: always
    networks:
      - loadbalancer-network
    scale: 4

  mongodb:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - noSqlData:/data/db
  mariadb:
    image: mariadb
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      # user name: root
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - sqlData:/var/lib/mysql
  calendarapi:
    build:
      context: src/calendar-backend
      dockerfile: Calendar.Api/Dockerfile
    depends_on:
      mongodb:
        condition: service_started
    restart: always
    ports:
      - 4000:80
    networks:
      - backend
    environment:
      MONGODB_CONNECTIONSTRING: mongodb://mongodb:27017/

volumes:
  noSqlData:
  sqlData:

networks:
  backend:
  loadbalancer-network:
    driver: bridge

