# start container: docker compose up -d --build
# stop container: docker compose down

# Set environments, label and command in docker-compose.override.yml

version: "3.9"

services:
  # calendar api
  calendar.api:
    build:
      context: src/calendar-backend
      dockerfile: Calendar.Api/Dockerfile
    depends_on:
      mongodb:
        condition: service_started
      keycloak:
        condition: service_started
      postgressdb:
        condition: service_healthy
      grafana:
        condition: service_started
    restart: on-failure:5
    networks:
      - backend
      - frontend
    ports:
      - 4000:80

  # calendar client
  client:
    build: 
      context: ./src/calendar-client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:4000
        - VITE_OIDC_CLIENT_SECRET=Wo9T9nS0ebJbUpVso6wpOGgVluQaqajA
        - VITE_OIDC_AUTHORITY=http://localhost:8080/realms/Calendar
        - VITE_OIDC_REDIRECT_URL=http://localhost:3000
    restart: always
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - frontend
    ports:
      - 3000:80

  # mongo db
  mongodb:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - ./config/mongodb/logs:/var/log/mongodb:rw
      - ./config/mongodb/init:/docker-entrypoint-initdb.d/:ro
  mongodbexporter:
    image: percona/mongodb_exporter:0.39
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - backend
    ports:
      - 9216:9216
    
  # keycloak authentication
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    restart: on-failure:1
    depends_on:
      postgressdb:
        condition: service_healthy
      mongodb:
        condition: service_started
      grafana:
        condition: service_started
    networks:
      - frontend
      - backend
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import:ro
    ports:
      - 8080:8080
  # postgres db
  postgressdb:
      image: "postgres:alpine3.18"
      restart: always
      networks:
        - backend
      ports:
        - "5432:5432"
      volumes:
        - postgress-data:/var/lib/postgresql/data
        - ./config/postgres/:/docker-entrypoint-initdb.d/:wr
        # - ./config/postgres/logs:/var/log/postgresql:rw
  
  # seq logging
  grafana:
    image: grafana/grafana-oss
    restart: always
    depends_on:
      - promtail
      - prometheus
    ports:
      - "5700:3000"
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./config/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml:ro
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    restart: always
    depends_on:
      - mongodbexporter
    networks:
      - backend
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki
    networks:
      - backend
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/loki-config.yml:ro
  
  promtail:
    image: grafana/promtail
    depends_on:
      - loki
    networks:
      - backend
    volumes:
      - ./config/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    
volumes:
  mongodb-data:
    driver: local
  postgress-data:
    driver: local
  grafana-data:
    driver: local
  

networks:
  backend:
  frontend:
    driver: bridge
# dotnet dev-certs https -ep $env:USERPROFILE\.aspnet\https\aspnetapp.pfx
