# start container: docker compose up -d --build
# stop container: docker compose down
version: "3.9"

services:
  client:
    build: ./src/calendar-client
    restart: always
    networks:
      - frontend
    ports:
      - 3005:80
  mongodb:
    image: mongo:latest
    restart: always
    # networks:
    #   - backend
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      CALENDAR_PASSWORD: ${CALENDAR_PASSWORD:-calendar}
    volumes:
      - ./database/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
  mariadb:
    image: mariadb
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      # user name: root
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - mariadb-data:/var/lib/mysql
  calendarapi:
    build:
      context: src/calendar-backend
      dockerfile: calendar-api/Dockerfile
    depends_on:
      mongodb:
        condition: service_started
    restart: always
    networks:
      - backend
      - frontend
    ports:
      - 4000:80
    environment:
      MONGODB_CONNECTIONSTRING: mongodb://mongodb:27017/

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
  mariadb-data:

networks:
  backend:
  frontend:

