version: '3.9'

volumes:
  redisinsight:

services:
  calendarapi:
    environment:
      MONGODB_CONNECTIONSTRING: mongodb://mongodb:27017/
      TZ: Europe/Berlin
    # labels:
    # - 'traefik.enable=true'
    # - 'traefik.http.routers.keycloak.rule=Host(`api.${DOMAIN}`)'
    # - 'traefik.http.routers.keycloak.entrypoints=https'
  client:
    environment:
     TZ: Europe/Berlin
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.keycloak.rule=Host(`${DOMAIN}`)'
    #   - 'traefik.http.routers.keycloak.entrypoints=https'
  
  # mariadb:
  #   environment:
  #     # user name: root
  #     MARIADB_ROOT_PASSWORD: example
  #     TZ: Europe/Berlin
  
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      TZ: Europe/Berlin
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5

  keycloak:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    command:
      - "start-dev"
      - "--db=postgres"
      - "--features=token-exchange"
      - "--db-url=jdbc:postgresql://posgressdb/keycloak" 
      - "--db-username=keycloak"
      - "--db-password=${MASTER_PW}"
      # - "--https-key-store-file=<file>"
      # - "--https-key-store-password=<password>"
    environment:
      TZ: Europe/Berlin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${MASTER_PW}
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.keycloak.rule=Host(`keycloak.${DOMAIN}`)'
    #   - 'traefik.http.routers.keycloak.entrypoints=https'
    #   - 'traefik.http.routers.keycloak.tls=true'
    #   - 'traefik.http.routers.keycloak.tls.certresolver=letsencrypt'
    #   - 'traefik.http.middlewares.keycloak.forwardauth.address=http://keycloak:9091/api/authz/forward-auth?authelia_url=https://keycloak.${DOMAIN}'  # yamllint disable-line rule:line-length
    #   - 'traefik.http.middlewares.keycloak.forwardauth.trustForwardHeader=true'
    #   - 'traefik.http.middlewares.keycloak.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
    # tty: true
    # healthcheck:
    #   ## In production the healthcheck section should be commented.
    #   disable: true
  posgressdb:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=${MASTER_PW}
      - POSTGRES_USER=keycloak
  # traefik:
  #   environment:
  #     TZ: Europe/Berlin
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)'
  #     - 'traefik.http.routers.api.entrypoints=http'
  #     - 'traefik.http.routers.api.service=api@internal'
  #     - 'traefik.http.routers.api.tls=true'
  #     - 'traefik.http.routers.api.tls.certresolver=letsencrypt'
  #     - 'traefik.http.routers.api.middlewares=keycloak@docker'
  #   command:
  #     - '--api'
  #     - '--providers.docker=true'
  #     - '--providers.docker.exposedByDefault=false'
  #     - '--entrypoints.http=true'
  #     - '--entrypoints.http.address=:80'
  #     - '--entrypoints.http.http.redirections.entrypoint.to=https'
  #     - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
  #     - '--entrypoints.https=true'
  #     - '--entrypoints.https.address=:443'
  #     - '--certificatesResolvers.letsencrypt.acme.email=hummelm.tin21@student.dhbw-heidenheim.de'
  #     - '--certificatesResolvers.letsencrypt.acme.storage=/etc/traefik/acme.json'
  #     - '--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=http'
  #     - '--log=true'
  #     - '--log.level=DEBUG'