# start container: docker compose up -d --build
# stop container: docker compose down
version: "3.9"

services:
  client:
    build: ./src/calendar-client
    restart: always
    networks:
      - frontend
    ports:
      - 3005:80
  mongodb:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - noSqlData:/data/db
  mariadb:
    image: mariadb
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      # user name: root
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - sqlData:/var/lib/mysql

volumes:
  noSqlData:
  sqlData:

networks:
  backend:
  frontend:

