# The given YAML configuration is specifying various settings for a service called Loki. Here is a
# breakdown of the different sections:
auth_enabled: false

# The `server` section in the YAML configuration is specifying the settings for the Loki server.
server:
  http_listen_port: 3100
  grpc_listen_port: 9096

# The `common` section in the YAML configuration is specifying common settings for the Loki service.
common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# The `query_range` section in the YAML configuration is specifying the settings for the results cache in the Loki service.
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

# The `schema_config` section in the YAML configuration is specifying the schema configuration for the
# Loki service. It defines the configuration for storing and indexing log data.
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# The `ruler` section in the YAML configuration is specifying the URL of the Alertmanager service that
# the Loki service should send alerts to. The `alertmanager_url` property is set to
# `http://localhost:9093`, which means that the Loki service will send alerts to the Alertmanager service running on the local machine at port 9093.
ruler:
  alertmanager_url: http://localhost:9093
