name: Docker Image CI

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build
    - name: Test the docker compose
      run: docker compose up --no-color --quiet-pull --force-recreate
    - name: Remove composed
      run: docker compose down -v
